version: '3'
services:
  # container backend services
  todoback:
    image: todobackend
    restart: always
    ports:
      - 3001:3001
  # container frontend services
  todofront:
    image: todofrontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
     - REACT_APP_API_HOST=todoback
  #container tests services
  todotests:
    image: todotests
    restart: always
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
